### ISSUE TITLE
我想读取单元格背景颜色值

### ISSUE THREAD

**Issue by hohnworld** [zurmokeeper/excelize#15]
# 我想读取单元格背景，我给单元格设置了单元格颜色的
```js
console.log(cell.style.fill.bgColor)
//输出{indexed: 64}，没有获取到具体的颜色值argb，譬如应该输出{indexed: 64,argb:'#ff00ff00'}这样的
```
[aaabbb.xlsx](https://github.com/zurmokeeper/excelize/files/12098010/aaabbb.xlsx)

**Comment by zurmokeeper** [comment]
@hohnworld 能贴下你的完整代码吗？

**Comment by hohnworld** [comment]
```js
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <script src="./exceljs.min.js"></script>
    <script src="./moment.js"></script>
  </head>
  <body>
    <input type="file" id="file" onchange="test()" />
    <script>
      async function test() {
        if (event.target.files.length > 0) {
          const file = event.target.files[0];
          console.log(file);
          event.target.value = "";
          console.time();
          var reader = new FileReader();
          reader.onloadend = function (event) {
            var arrayBuffer = reader.result;
            var workbook = new ExcelJS.Workbook();
            workbook.xlsx.load(arrayBuffer).then(function (workbook) {
              const sheet = workbook.worksheets[0];
              const cell=sheet.getCell(1,1)
              console.log(cell.style.fill.bgColor);
            });
          };
          reader.readAsArrayBuffer(file);
        }
      }
    </script>
  </body>
</html>

```

**Comment by hohnworld** [comment]
> ```js
> <!DOCTYPE html>
> <html lang="en">
>   <head>
>     <meta charset="UTF-8" />
>     <meta http-equiv="X-UA-Compatible" content="IE=edge" />
>     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>     <title>Document</title>
>     <script src="./exceljs.min.js"></script>
>     <script src="./moment.js"></script>
>   </head>
>   <body>
>     <input type="file" id="file" onchange="test()" />
>     <script>
>       async function test() {
>         if (event.target.files.length > 0) {
>           const file = event.target.files[0];
>           console.log(file);
>           event.target.value = "";
>           console.time();
>           var reader = new FileReader();
>           reader.onloadend = function (event) {
>             var arrayBuffer = reader.result;
>             var workbook = new ExcelJS.Workbook();
>             workbook.xlsx.load(arrayBuffer).then(function (workbook) {
>               const sheet = workbook.worksheets[0];
>               const cell=sheet.getCell(1,1)
>               console.log(cell.style.fill.bgColor);
>             });
>           };
>           reader.readAsArrayBuffer(file);
>         }
>       }
>     </script>
>   </body>
> </html>
> ```

## 测试文件如提交问题的附件aaabbb.xlsx
## 引入的exceljs.min.js是另一个项目npm i @zurmokeeper/exceljs安装后node_modules\@zurmokeeper\exceljs\dist中的

**Comment by zurmokeeper** [comment]
@hohnworld 暂时只是简单看了下，从 cell.style.fill.fgColor.argb 可以拿到，颜色和excel里的是一样的

**Comment by hohnworld** [comment]
几次输入cell.style.fill时候就看到了fgColor前景色，却去获取bgColor背景色，忽略了fgColor，非常非常感谢
