### ISSUE TITLE
[Q] xlsx.load(buffer) 时卡住，cpu 100%

### ISSUE THREAD

**Issue by xliez** [zurmokeeper/excelize#23]
## 💬 Questions and Help

```ts
import { Workbook } from '@zurmokeeper/exceljs';

function readFile(fileRes: any) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsArrayBuffer(fileRes);
    reader.onload = () => {
      resolve(reader.result);
    };
  });
}

export const loadExcel = async (file: any) => {
  const buffer = await readFile(file);
  console.log('[ buffer ]-15', buffer);

  const workbook = new Workbook();
  console.log('[ workbook ]-18', workbook);
  const book = await workbook.xlsx.load(buffer as Buffer);
  console.log('[ book ]-18', book);
};


```

没有报错，标签页卡死，标签页 CPU 100%
console.log('[ book ]-18', book) 这一行执行不到

**Comment by zurmokeeper** [comment]
@xliez 可以提供下excel文件吗？

**Comment by xliez** [comment]
发送到你邮箱了

**Comment by zurmokeeper** [comment]
@xliez 这个问题和这个issue #6 是一样，都是数据有限性验证设置的太大了， sqref="BT2:BT1048576"， sqref="K2:K1048576" 还有更多，如下图， 这几个圈出来的字段（还有一些没圈出来的字段）就是设置了数据有限性验证的，一整列都设置了，现在代码处理数据有限性验证还有点问题，如果很大就会卡住。


![image](https://github.com/zurmokeeper/excelize/assets/25943604/b37c0b9c-a2bf-4bda-a7e5-c86bb7bbee1c)



有几个方案处理：
1：如果你不需要读取数据有限性验证里的设置，可以照这里的操作，先把所有的数据有限性验证都清除了，应该就能读了
2：现在只是 “批量上传模板”这个sheet 设置了数据有限性验证，如果不需要读这个sheet，可以把这个sheet删了，应该就能读了
3：可能得等会，我这个新功能（New xlsx option for ignoring certain nodes for improved performance） #22 ，就是暂时先用来解决这个问题的，正在做了

**Comment by xliez** [comment]
好的，非常感谢解答！

**Comment by zurmokeeper** [comment]
@xliez V4.4.6 已经发布了，可以更新体验下，已经可以通过忽略数据有效性节点的方式来暂时处理你这个问题，可以看下这里 [https://github.com/zurmokeeper/excelize/releases/tag/4.4.6](url)

**Comment by xliez** [comment]
> @xliez V4.4.6 已经发布了，可以更新体验下，已经可以通过忽略数据有效性节点的方式来暂时处理你这个问题，可以看下这里 [https://github.com/zurmokeeper/excelize/releases/tag/4.4.6](url)

好的，感谢帮忙🌹
