### ISSUE TITLE
Respecting Original Contributions: An Appeal to Retain Git History

### ISSUE THREAD

**Issue by Siemienik** [zurmokeeper/excelize#26]
Dear Excelize,

I've noticed that your project incorporates code from the https://github.com/exceljs/exceljs library. However, the entire Git history has been removed, which subsequently erased information about the original authors of the project. I would like to emphasize the importance of recognizing and appreciating the efforts and contributions of those who have dedicated their time and energy to develop this library over the years.

Maintaining the project's history not only pays homage to its creators but also serves as a key to understanding the evolution of the code and the rationale behind various changes. It is invaluable information for other developers who might want to use or further develop your project.

With all due respect, I understand that each project might have its reasons for certain decisions. Nonetheless, I urge you to consider restoring this history or, at the very least, acknowledging the original authors in your documentation or on your project's main page. Collaboration and recognition within the open-source community play a pivotal role and help foster a healthy ecosystem for all its users.

Thank you for your attention, and I wish you success in your ongoing development endeavors.

Best regards,
Pawel Siemienik

**Comment by zurmokeeper** [comment]
@Siemienik 

Thanks for the reminder, I didn't mean to create a new project, it's just that I didn't know how to do it at first, and thought I was going to have to create a new project to continue. I did state in the readme.md where this project originated from, and it says so in this screenshot below, so I'm not sure if that matches, or if I need to do something more?

![image](https://github.com/zurmokeeper/excelize/assets/25943604/616c2404-be8b-4c64-a076-6448ec8be983)
