### ISSUE TITLE
Cannot Open Encrypted Files

### ISSUE THREAD

**Issue by TL-SWFT** [zurmokeeper/excelize#29]
I am trying to read an encrypted XLSX file with the following code, but got an error saying "TypeError: Unknown cipher". I am sure that file can be opened by Excel with password "123456". I'm not sure what is wrong. Would anyone please help me investigate?

```js
const workbook = new ExcelJS.Workbook();

const res = await workbook.xlsx.readFile("123 copy.xlsx", {
  password: "123456",
});
```

- OS: Windows 11 22000.2538
- Package Version: 4.4.6
- Excel Version: Microsoft® Excel® 适用于 Microsoft 365MSO (版本 2309 Build 16.0.16827.20166) 64 [位]

P.S. Here is a link to the file I tried to open:

- [123 copy.xlsx](https://github.com/zurmokeeper/excelize/files/13050418/123.copy.xlsx)

**Comment by TL-SWFT** [comment]
sorry,I omitted the error message.the error is: Uncaught (in promise) TypeError: Unknown cipher

**Comment by zurmokeeper** [comment]
@TL-SWFT Hi, I'm using your file and the code is readable properly wow. Can you record a screen?

**Comment by TL-SWFT** [comment]
I'm very sorry. After testing, it is found that the problem occurred in the Deno environment. I was unable to read correctly using Deno, but I could read normally in the Node.js environment. @zurmokeeper

**Comment by zurmokeeper** [comment]
@TL-SWFT I see, can you provide the version of deno and some complete code? I'll see if I can come up with a version that supports deno.

**Comment by TL-SWFT** [comment]
Deno Version: 1.37.2
The complete code is as follows: 
```js
#! set NO_COLOR=true && deno run -A

import ExcelJS from "npm:@zurmokeeper/exceljs@4.4.6";

const workbook = new ExcelJS.Workbook();
const res = await workbook.xlsx.readFile("123.xlsx",{password:"123456"});
console.log(res);
```
@zurmokeeper

**Comment by zurmokeeper** [comment]
@TL-SWFT thanks
