### ISSUE TITLE
[BUG] Internal hyperlink does not work on wps office

### ISSUE THREAD

**Issue by dzzzzzy** [zurmokeeper/excelize#4]
## 🐛 Bug Report

Lib version: 4.4.1

![image](https://github.com/zurmokeeper/excelize/assets/19354905/053a1e62-7440-4fcd-90e1-005b100d1268)

## Steps To Reproduce

```javascript
const wb = new ExcelJS.Workbook();
const ws1 = wb.addWorksheet('Sheet1');
const ws2 = wb.addWorksheet('Sheet2');

// internal link
ws1.getCell('A1').value = { text: 'Sheet2', hyperlink: '#\'Sheet2\'!A1' };
```

## Possible solution (optional, but very helpful):

```javascript

```

**Comment by zurmokeeper** [comment]
@dzzzzzy There is indeed this problem, I'll follow up, thanks。

**Comment by zurmokeeper** [comment]
@dzzzzzy Already found the problem, but to deal with google sheet compatibility and write test cases need some time, may be later to release the new version.

**Comment by zurmokeeper** [comment]
@dzzzzzy A new version has been released, see readme for details
